// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220914091440_UpdateTable")]
    partial class UpdateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Body", b =>
                {
                    b.Property<int>("IDocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bank_acc_numbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bank_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bankey_numbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beg_Temp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birth_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birth_plc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrShft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dist_DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dist_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DptmCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmplCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmplType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IC_numbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IC_numbr_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDocNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Job_Cod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_numbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prov_DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prov_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PstnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_Dist_DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_Dist_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_Prov_DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_Prov_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_Street_numbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_Wards_DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_Wards_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street_numbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wards_DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wards_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDocID");

                    b.HasIndex("IDocNo");

                    b.ToTable("Idoc_Item");
                });

            modelBuilder.Entity("WebAPI.Header", b =>
                {
                    b.Property<string>("IDocNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDOCType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SITECode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("IDocNo");

                    b.ToTable("Idoc_Header");
                });

            modelBuilder.Entity("WebAPI.Body", b =>
                {
                    b.HasOne("WebAPI.Header", "H_IDoc_No")
                        .WithMany()
                        .HasForeignKey("IDocNo");

                    b.Navigation("H_IDoc_No");
                });
#pragma warning restore 612, 618
        }
    }
}
